## redis salve2
apiVersion: v1
kind: Service
metadata:
  namespace: zln
  name: redis-salve2
  labels:
    app: redis-salve2
spec:
  ports:
    - port: 6379
      nodePort: 32704
      targetPort: 6379
  selector:
    app: redis-salve2
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-salve2
  namespace: zln
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-salve2
  template:
    metadata:
      labels:
        app: redis-salve2
    spec:
      containers:
        - name: redis-salve2
          image: hub.pml.com/zln/redis:6.0.4
          ports:
            - containerPort: 6379
          command:
            - "redis-server"
          args:
            - "/etc/redis/redis.conf"
            - "--requirepass 'admin'"
            - "--slaveof redis-master 6379"
            - "--masterauth admin"
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 0.5
              memory: 500Mi
          volumeMounts:
            - name: date-config
              mountPath: /etc/localtime
            - name: redis-data
              mountPath: /data
            - name: redis-conf
              mountPath: /etc/redis/
      volumes:
        - name: date-config
          hostPath:
            path: /etc/localtime
        - name: redis-data
          hostPath:
            path: /zln/redis-salve2/data
        - name: redis-conf
          hostPath:
            path: /zln/redis-salve2/conf

