apiVersion: v1
kind: Service
metadata:
  namespace: zln
  name: redis
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      nodePort: 32701
      targetPort: 6379
  selector:
    app: redis
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: zln
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        kubernetes.io/hostname: zz-node1
      containers:
        - name: redis
          image: hub.pml.com/zln/redis:6.0.4
          ports:
            - containerPort: 6379
          command:
            - "redis-server"
          args:
            - "/etc/redis/redis.conf"
            - "--requirepass 'admin'"
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 0.5
              memory: 500Mi
          volumeMounts:
            - name: date-config
              mountPath: /etc/localtime
            - name: redis-data
              mountPath: /data
              readOnly: false
            - name: redis-conf
              mountPath: /etc/redis/
              readOnly: false
      volumes:
        - name: date-config
          hostPath:
            path: /etc/localtime
        - name: redis-conf
          configMap:
            items:
              - key: redis.conf
                path: redis.conf
            name: redis-configmap

  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: "redis-master-storage-class"
        resources:
          requests:
            storage: 4Gi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-configmap
  namespace: zln
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  redis.conf: |
    # 根据需求去修改端口
    port 6379
    # 日志文件
    logfile "/data/redis_6379.log"
    # 开启AOF持久化
    appendonly yes
    # 数据保存目录
    dir /data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-master
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "redis-master-storage-class"
  nfs:
    # real share directory
    path: /nfs/redis-master-133/data
    # nfs real ip
    server: 172.171.15.74



