apiVersion: v1
kind: Service
metadata:
  namespace: zln
  name: redis-salve
  labels:
    app: redis-salve
spec:
  ports:
    - port: 6379
      nodePort: 32704
      targetPort: 6379
  selector:
    app: redis-salve
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-salve
  namespace: zln
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-salve
  serviceName: redis-salve
  template:
    metadata:
      labels:
        app: redis-salve
    spec:
      containers:
        - name: redis-salve
          image: hub.pml.com/zln/redis:6.0.4
          ports:
            - containerPort: 6379
          command:
            - "redis-server"
          args:
            - "/etc/redis/redis.conf"
            - "--requirepass 'admin'"
            - "--slaveof redis-master 6379"
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 0.5
              memory: 500Mi
          volumeMounts:
            - name: date-config
              mountPath: /etc/localtime
            - name: redis-data
              mountPath: /data
              readOnly: false
            - name: redis-conf
              mountPath: /etc/redis/
              readOnly: false
      volumes:
        - name: date-config
          hostPath:
            path: /etc/localtime
        - name: redis-conf
          configMap:
            items:
              - key: redis-salve.conf
                path: redis.conf
            name: redis-salve-configmap

  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: "redis-salve-storage-class"
        resources:
          requests:
            storage: 4Gi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-salve-configmap
  namespace: zln
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  redis-salve.conf: |
    # 根据需求去修改端口
    port 6379
    # 日志文件
    logfile "/data/redis_6379.log"
    # 开启AOF持久化
    appendonly yes
    # 数据保存目录
    dir /data
    # 主节点认证
    masterauth admin
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-salve-0
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "redis-salve-storage-class"
  nfs:
    # real share directory
    path: /nfs/redis-salve-0/data
    # nfs real ip
    server: 172.171.15.74
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-salve-1
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "redis-salve-storage-class"
  nfs:
    # real share directory
    path: /nfs/redis-salve-1/data
    # nfs real ip
    server: 172.171.15.74
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-salve-2
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "redis-salve-storage-class"
  nfs:
    # real share directory
    path: /nfs/redis-salve-2/data
    # nfs real ip
    server: 172.171.15.74

