apiVersion: v1
kind: Service
metadata:
  namespace: zln
  name: redis-sentinel
  labels:
    app: redis-sentinel
spec:
  ports:
    - port: 6379
      nodePort: 32705
      targetPort: 6379
  selector:
    app: redis-sentinel
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sentinel
  namespace: zln
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  serviceName: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      containers:
        - name: redis-sentinel
          image: hub.pml.com/zln/redis:6.0.4
          ports:
            - containerPort: 6379
          command:
            - "redis-sentinel"
          args:
            - "/etc/redis/redis.conf"
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 0.5
              memory: 500Mi
          volumeMounts:
            - name: date-config
              mountPath: /etc/localtime
            - name: redis-conf
              mountPath: /etc/redis/
              readOnly: false
      volumes:
        - name: date-config
          hostPath:
            path: /etc/localtime
        - name: redis-conf
          configMap:
            items:
              - key: redis-sentinel.conf
                path: redis.conf
            name: redis-sentinel-configmap
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-sentinel-configmap
  namespace: zln
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  redis-sentinel.conf: |
    # 根据需求去修改端口
    port 6379
    # 日志文件
    logfile "/data/redis_6379.log"
    # 开启AOF持久化
    appendonly yes
    # 数据保存目录
    dir /data
    # 哨兵相关配置
    sentinel monitor mymaster 10.254.220.165 6379 2
    #30000毫秒ping不通认为出现问题
    sentinel down-after-milliseconds mymaster 30000
    #选择了新的master之后老的slave会对新的slave进行复制，1代表每次只有一个slave进行复制，减轻master压力
    sentinel parallel-syncs mymaster 1
    #故障转移时间
    sentinel failover-timeout mymaster 180000
---